In [16]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\honor\anaconda3\lib\site-packages (2.9.10)

In [20]:
import psycopg2

In [78]:
conn = psycopg2.connect(host= "rc1b-7ng6ih3jte3824x8.mdb.yandexcloud.net",
                       port= 6432,
                       database= "demo",
                       user= "student",
                       password= "student!")

In [80]:
cur = conn.cursor()

In [84]:
cur.execute(sql)

In [88]:
import pandas as pd

In [90]:
cur.execute(sql)

In [110]:
import sqlalchemy

In [114]:
from sqlalchemy import create_engine, text

In [116]:
def connection_yandex_cloud_demo(echo):
    """Connection to DataBase demo"""
    login = 'student'
    password = 'student!'
    host = 'rc1b-7ng6ih3jte3824x8.mdb.yandexcloud.net'
    port = '6432'
    db_name = 'demo'
    return create_engine(f'postgresql://{login}:{password}@{host}:{port}/{db_name}', echo=echo)

In [118]:
engine = connection_yandex_cloud_demo(echo=True)

In [120]:
import pandas as pd
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [94]:
sql = """SELECT count(*) 
        FROM booking.aircrafts_data
      ;"""

In [126]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 15:50:01,927 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 15:50:01,936 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 15:50:01,937 INFO sqlalchemy.engine.Engine [generated in 0.00094s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D2927B9130>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 15:50:01,938 INFO sqlalchemy.engine.Engine SELECT count(*)
        FROM booking.aircrafts_data
      ;
2025-07-20 15:50:01,939 INFO sqlalchemy.engine.Engine [generated in 0.00152s] {}
2025-07-20 15:50:02,011 INFO sqlalchemy.engine.Engine COMMIT

In [130]:
df.head()

   count
0      9

In [132]:
sql = """
SELECT avg(range) as "Средняя дальность"
  FROM booking.aircrafts_data
 ; """

In [136]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:08:55,805 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:08:55,806 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:08:55,806 INFO sqlalchemy.engine.Engine [cached since 1134s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D2921109E0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:08:55,807 INFO sqlalchemy.engine.Engine
SELECT avg(range) as "Средняя дальность"
  FROM booking.aircrafts_data
 ;
2025-07-20 16:08:55,807 INFO sqlalchemy.engine.Engine [generated in 0.00064s] {}
2025-07-20 16:08:55,857 INFO sqlalchemy.engine.Engine COMMIT

In [138]:
df.head()

   Средняя дальность
0        5344.444444

In [140]:
sql = """
SELECT max(range) as "Максимальная дальность"
  FROM booking.aircrafts_data
 ;"""

In [142]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:11:14,960 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:11:14,961 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:11:14,963 INFO sqlalchemy.engine.Engine [cached since 1273s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D2927BA8D0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:11:14,963 INFO sqlalchemy.engine.Engine
SELECT max(range) as "Максимальная дальность"
  FROM booking.aircrafts_data
 ;
2025-07-20 16:11:14,964 INFO sqlalchemy.engine.Engine [generated in 0.00067s] {}
2025-07-20 16:11:15,037 INFO sqlalchemy.engine.Engine COMMIT

In [144]:
df.head()

   Максимальная дальность
0                   11100

In [146]:
sql = """
select count(airport_code)
  from booking.airports_data
 ;"""

In [148]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:12:41,478 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:12:41,481 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:12:41,481 INFO sqlalchemy.engine.Engine [cached since 1360s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D29290DAF0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:12:41,482 INFO sqlalchemy.engine.Engine
select count(airport_code)
  from booking.airports_data
 ;
2025-07-20 16:12:41,483 INFO sqlalchemy.engine.Engine [generated in 0.00072s] {}
2025-07-20 16:12:41,533 INFO sqlalchemy.engine.Engine COMMIT

In [150]:
df.head()

   count
0    104

In [152]:
sql = """
select avg(total_amount),percentile_cont(0.5) WITHIN GROUP (ORDER BY total_amount) AS median, mode() WITHIN GROUP (ORDER BY total_amount) as moda
  from booking.bookings
 group by total_amount 
 ;"""

In [154]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:14:00,474 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:14:00,475 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:14:00,476 INFO sqlalchemy.engine.Engine [cached since 1439s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D29290F4A0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:14:00,477 INFO sqlalchemy.engine.Engine
select avg(total_amount),percentile_cont(0.5) WITHIN GROUP (ORDER BY total_amount) AS median, mode() WITHIN GROUP (ORDER BY total_amount) as moda
  from booking.bookings
 group by total_amount
 ;
2025-07-20 16:14:00,478 INFO sqlalchemy.engine.Engine [generated in 0.00092s] {}
2025-07-20 16:14:12,166 INFO sqlalchemy.engine.Engine COMMIT

In [156]:
df.head()

      avg  median    moda
0  3400.0  3400.0  3400.0
1  3700.0  3700.0  3700.0
2  3800.0  3800.0  3800.0
3  4000.0  4000.0  4000.0
4  4100.0  4100.0  4100.0

In [158]:
sql = """
select * 
  from booking.bookings
 order by total_amount desc 
 limit 5
 ;"""

In [160]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:17:01,639 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:17:01,641 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:17:01,641 INFO sqlalchemy.engine.Engine [cached since 1620s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D29298FC20>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:17:01,642 INFO sqlalchemy.engine.Engine
select *
  from booking.bookings
 order by total_amount desc
 limit 5
 ;
2025-07-20 16:17:01,642 INFO sqlalchemy.engine.Engine [generated in 0.00058s] {}
2025-07-20 16:17:02,060 INFO sqlalchemy.engine.Engine COMMIT

In [162]:
df.head()

  book_ref                 book_date  total_amount
0   319D65 2016-11-22 04:15:00+00:00     1308700.0
1   BC7A15 2017-01-22 11:33:00+00:00     1211000.0
2   3B54BB 2017-07-05 14:08:00+00:00     1204500.0
3   C59FE9 2017-03-23 00:59:00+00:00     1165300.0
4   4929FD 2017-03-26 22:16:00+00:00     1144000.0

In [164]:
sql = """
 select count(boarding_no) as "Кол-во посадочных талонов"
  from booking.boarding_passes
;"""

In [166]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:23:29,963 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:23:29,964 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:23:29,966 INFO sqlalchemy.engine.Engine [cached since 2008s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D29290FE90>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:23:29,966 INFO sqlalchemy.engine.Engine
 select count(boarding_no) as "Кол-во посадочных талонов"
  from booking.boarding_passes
;
2025-07-20 16:23:29,967 INFO sqlalchemy.engine.Engine [generated in 0.00071s] {}
2025-07-20 16:24:07,264 INFO sqlalchemy.engine.Engine COMMIT

In [168]:
df.head()

   Кол-во посадочных талонов
0                    7925812

In [171]:
sql = """
select count(fare_conditions)
  from booking.ticket_flights
 where fare_conditions = 'Business'
 ;"""

In [173]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:25:51,434 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:25:51,436 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:25:51,437 INFO sqlalchemy.engine.Engine [cached since 2150s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D28E8828D0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:25:51,439 INFO sqlalchemy.engine.Engine
select count(fare_conditions)
  from booking.ticket_flights
 where fare_conditions = 'Business'
 ;
2025-07-20 16:25:51,439 INFO sqlalchemy.engine.Engine [generated in 0.00092s] {}
2025-07-20 16:26:34,309 INFO sqlalchemy.engine.Engine COMMIT

In [175]:
df.head()

    count
0  859656

In [178]:
sql = """
 select fare_conditions, avg(amount)
   from booking.ticket_flights tf  
 group by fare_conditions 
 ;"""

In [180]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:28:42,827 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:28:42,828 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:28:42,829 INFO sqlalchemy.engine.Engine [cached since 2321s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D2927BB9E0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:28:42,829 INFO sqlalchemy.engine.Engine
 select fare_conditions, avg(amount)
   from booking.ticket_flights tf
 group by fare_conditions
 ;
2025-07-20 16:28:42,831 INFO sqlalchemy.engine.Engine [generated in 0.00072s] {}
2025-07-20 16:29:20,504 INFO sqlalchemy.engine.Engine COMMIT

In [182]:
df.head()

  fare_conditions           avg
0        Business  51557.399820
1         Comfort  32724.546137
2         Economy  16031.309073

In [185]:
sql = """
 SELECT avg(scheduled_arrival - scheduled_departure)
  FROM booking.flights f 
  ;"""

In [187]:
with engine.begin() as connection:
    df = pd.read_sql(text(sql), con = connection)

2025-07-20 16:31:22,204 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-20 16:31:22,205 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-07-20 16:31:22,205 INFO sqlalchemy.engine.Engine [cached since 2480s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x000001D2921B9520>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-07-20 16:31:22,207 INFO sqlalchemy.engine.Engine
 SELECT avg(scheduled_arrival - scheduled_departure)
  FROM booking.flights f
  ;
2025-07-20 16:31:22,207 INFO sqlalchemy.engine.Engine [generated in 0.00080s] {}
2025-07-20 16:31:22,330 INFO sqlalchemy.engine.Engine COMMIT

In [189]:
df.head()

                     avg
0 0 days 02:08:21.828108